### ISSUE TITLE
Accounts/ rul are case-sensitive, preventing users from finding their accounts

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/explorer-frontend#150]
Users can't access their accounts in the explorer because the explorer is case-sensitive, while accounts in the App (that is, the ones that users paste into the tap) are in all-lowercase by default. So, for example:
This address doesn't show up: https://explorer-126.spacemesh.io/accounts/0xfbff2d3cf4aca3fad08c1e826c6b118e00cd7fa7
But this one does: https://explorer-126.spacemesh.io/accounts/0xfBFF2D3Cf4aCA3faD08C1e826C6b118E00Cd7fA7

**Comment by avive** [comment]
I can confirm this is an issue.

**Comment by Motzart** [comment]
Search is strict match

**Comment by avive** [comment]
it should be changed to be case insensitive.

**Comment by Motzart** [comment]
I can’t do this from frontend part because address used lower and upper letters, if i change all of them to lowerCase then we cant find any address, this issue could be solve on the backend

it doesn’t matter  it’s url or it will be search field
I got this address from the backend, that's why I return in this format
so waiting when backend solve this part

**Comment by avive** [comment]
Confirmed fixed. Hex chars in urls can be any case.
