### ISSUE TITLE
Wrong balance displayed in accounts screen

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#158]
1. Clear explorer web app local browser cache
2. Navigate to https://explorer.spacemesh.io/accounts 
3. Scroll down until you see an account with 0 balance.
4. Click on that account to see details.

Result: correct balance is displayed. 

5. Go back to accounts page.
Result: correct balance is displayed (non-zero).

Devnet 207.

**Comment by mephistopheles1010** [comment]
It happens due to problem with node streaming api. 
Explorer front-end retrieve data from explorer api gateway, that balanced between  few explorer backe-ends, that receives data from different nodes.
According to issue https://github.com/spacemeshos/go-spacemesh/issues/2384, different nodes send different reward events to their explorer back-ends.
In this case sometimes on explorer interface(https://explorer.spacemesh.io/accounts) we can see different data.
Now It is fixed with https://github.com/spacemeshos/go-spacemesh/pull/2948. 
You can check it now on https://explorer.spacemesh.io/rewards, devnt: devnet-kirill-5. 
In general it works fine with explorer since 0.0.10 and node since v0.2.7-beta.0. 
This issue can be closed.

**Comment by avive** [comment]
I want to verify this but according to the discovery service metadata devnet-k-5 is using explorer 0.0.9.
