### ISSUE TITLE
Block page review

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#95]
- Title: `specific details for this block` -> `Block [short_hash]`.
- Subtitle: `specific details for this block.` -> `Details`.
- `Block Number` - make 0 for now. This will be the index of the block in the layer once the api supports this.
- Remove block end timestamp row.
- Change `block start timestamp` label to `block time`.
- Make the layer data item clickable to view this layer's page on click.
- Make the epoch data item clickable to view the epoch's page on click.
- `Total Transactions` -> `Transactions`.
- `Total Rewards` -> `Rewards`.
- Missing field: `Smesher` - The smesher who submitted this block to the mesh. Linkable to smesher's screen.
- Finality: 0% if layer is bigger then verified layer number. 99% if layer is equal or smaller to verified layer number.
- Total rewards data item: numerical. If no rewards then display `0` instead of `--`.
- `Total rewards value` data item. Units is coin. If 0 then display 0 SMH instead of `--`.
- `Hash` - display full block hash but w/o all the trailing 0s.
- Callout area: `Total Coin Rewards:` - remove `:` from label (like we did for all other screens). `txns` -> `Transactions`.
- Fix the number of transactions in callout. It is currently constant `000` even for a block with transactions. see: https://stage-explore.spacemesh.io/blocks/0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e000000000000000000000000

**Comment by despablos** [comment]
**Fixed all, except:**

_1. Block Number - make 0 for now. This will be the index of the block in the layer once the api supports this.
2. Missing field: Smesher - The smesher who submitted this block to the mesh. Linkable to smesher's screen.
3. Total rewards data item: numerical. If no rewards then display 0 instead of --.
4. Total rewards value data item. Units is coin. If 0 then display 0 SMH instead of --.
5. Hash - display full block hash but w/o all the trailing 0s.
6. Fix the number of transactions in callout. It is currently constant 000 even for a block with transactions. see: https://stage-explore.spacemesh.io/blocks/0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e000000000000000000000000_

**This issues will be fixed, after back-end fix.**
